indralab/depmap_analysis

- .gitignore
- db_nest_dict_to_jsons.py
- depmap_network_functions.py
- depmap_script.py
- expl_nest_dict_to_jsons.py
- scripts/populate_dropdown_from_remote_json.js
This PR implements belief score ranking for gene X in A-X-B interactions. Note that in this PR the address that points to the interaction dictionaries on S3 is changed and now points to a new directory (pre_release_Q3_depmap_20180730_db_explained_improved).
> Belief score sorting

- scripts/populate_dropdown_from_remote_json.js
This PR fixes:
1. Old jsons from S3 that didn't have the correct structure (uploaded new jsons to new directory) gave erroneous items in dropdown for B.
2. The output and output headers were not updating unless it was replaced by new output.
> Web output fix

- scripts/populate_dropdown_from_remote_json.js
This short PR resolves the issue of clashing button IDs that previously made multiple buttons that pointed to the same source did not produce any output.
> Resolved issue of clashing button IDs.

- scripts/populate_dropdown_from_remote_json.js
This PR solves [issue #18](https://github.com/johnbachman/depmap_analysis/issues/18) where there sometimes would be two dropdowns for AXB connections and for complex outputs.
> Solved double dropdown issue by adding new checkpoints.

- index.html
- scripts/populate_dropdown_from_remote_json.js
This PR updates JS and HTML to fix a bug that had the A-X-B output not working.
Also reduced size of page header.
> Page layout fix

- depmap_network_functions.py
- depmap_script.py
This PR updates the DepMap script with a range of new functionalities.
Highlights:
- Added filtering of cell lines for cell line data
- Added option to read cell line specific files
- Added option to consider genes explained as part of a pre-loaded file
- Various output improvements: file output, statistics and script logging
> Script Update

- depmap_analysis/network_functions/indra_network.py
- indra_depmap_service/query.html
This PR adds the option to search a path in both directions.
> Search both ways

- depmap_analysis/network_functions/indra_network.py
- indra_depmap_service/query.html
This PR adds an option which lets the user specify the path search is termination timeout.
> User timeout

- depmap_analysis/network_functions/indra_network.py
- depmap_analysis/network_functions/net_functions.py
- depmap_analysis/tests/test_indra_network.py
- indra_depmap_service/api.py
- indra_depmap_service/static/netSearch.js
- indra_depmap_service/templates/query_template.html
- indra_depmap_service/util.py
This PR adds several updates related to the network search frontend. Most important are:
- Search regulators/targets from a list of any length of targets/regulators.
- Add shared regulators output for web ui
- Add downloading of the statements of the path search on the web ui
- Allow any namespace for inputs (source, target, regulators, targets, etc)
- Add a gilda helper method to get top ranked name
- Add function to ping gilda
- Add new endpoints to handle checking of nodes' existence in network
- Move a lot of helper functions for the network search api to `indra_depmap_service.util.py`
- Bug fixes, added/improved docstrings and code formatting
> Frontend dev

- depmap_analysis/network_functions/indra_network.py
- indra_depmap_service/api.py
- indra_depmap_service/static/netSearch.js
- indra_depmap_service/templates/query_template.html
- indra_depmap_service/util.py
This PR provides the ability to share searches by creating a hash of the query which is then provided as a parameter on the main page, e.g. https://network.indra.bio?query=123456789
Results are stored on s3 and when a previous query is requested, the stored results are used instead of running the search again.
> Share search

- depmap_analysis/network_functions/famplex_functions.py
- depmap_analysis/network_functions/indra_network.py
- depmap_analysis/network_functions/net_functions.py
This PR adapts code to use the INDRA ontology graph added in https://github.com/sorgerlab/indra/pull/1100.
> Ontology graph

- depmap_analysis/network_functions/indra_network.py
- depmap_analysis/network_functions/net_functions.py
- indra_depmap_service/api.py
- indra_depmap_service/static/netSearch.js
This PR allows a client to change the maximum memory limit for the BFS endpoint.
A bug is also fixed where the provided namespaces for `terminal_ns` were previously not set to lowercase.
Depends on https://github.com/sorgerlab/indra/pull/1105
> BFS Update

- depmap_analysis/scripts/depmap_script2.py
- depmap_analysis/util/statistics.py
This PR adds `script_settings` to the DepMapExplainer attributes which contains which options the depmap script was run with, when available. This should make reproducing the run that created the DepMapExplainer object much more consistent.
> Explainer meta data

- depmap_analysis/network_functions/depmap_network_functions.py
- depmap_analysis/scripts/depmap_script2.py
- depmap_analysis/scripts/loop_reactome.py
- depmap_analysis/util/io_functions.py
This PR creates a script that checks if correlation pairs have matching reactome pathways. The function that calculates a size sample size of a correlation matrix given a desired amount of extracable pairs is moved to `depmap_network_functions.py`.
> Reactome matching

- depmap_analysis/network_functions/depmap_network_functions.py
- depmap_analysis/scripts/depmap_script.py
- depmap_analysis/scripts/depmap_script2.py
- depmap_analysis/scripts/expl_proportions.py
- depmap_analysis/scripts/gather_all_corr_stats.py
- depmap_analysis/scripts/loop_reactome.py
- depmap_analysis/util/aws.py
- depmap_analysis/util/io_functions.py
- indra_depmap_service/api.py
- indra_depmap_service/util.py
This PR adds pathlib usage in `io_functions.py` and also corrects a bug for S3 prefixes. A wrapper is also made for the file dumpers that check for file existence and creates parent directories as necessary.
> Pathlib usage

- depmap_analysis/network_functions/indra_network.py
- doc/indra_depmap_service/web_ui_introduction.rst
- indra_depmap_service/api.py
- indra_depmap_service/static/netSearch.js
- indra_depmap_service/templates/query_template.html
- indra_depmap_service/util.py
This PR adds a text box for entering the mesh ids to the query webpage, and then uses related hashes for filtering edges while finding open and closed paths.
> Add mesh ids text box

- indra_depmap_service/api.py
- indra_depmap_service/static/netSearch.js
- indra_depmap_service/templates/query_template.html
This PR updates the address to which the results link out to the INDRA DB.
> Update INDRA DB linkout

- depmap_analysis/network_functions/indra_network.py
- indra_depmap_service/api.py
This PR fixes a previously unhandled corner case when a search was done with all of the following fulfilled:
- A specific path length
- Breadth first search
- unweighted search
> Handle fixed length open, unweighted search

- depmap_analysis/network_functions/indra_network.py
This PR handles a specific case were NetworkX raises `NetworkXError` instead of `NodeNotFound`, which the query handling relies on to retry the same query with grounding normalization of the missing queries.
> Solve no such node error represented as NetworkXError

- depmap_analysis/network_functions/depmap_network_functions.py
- depmap_analysis/preprocessing/__init__.py
- depmap_analysis/preprocessing/depmap_preprocessing.py
- depmap_analysis/scripts/depmap_preprocessing.py
- depmap_analysis/scripts/depmap_script2.py
- depmap_analysis/scripts/depmap_script_expl_funcs.py
- depmap_analysis/util/io_functions.py
- depmap_analysis/util/statistics.py
This PR makes some substantial changes and updates, mostly to handle analysis of drug-drug correlations in the depmap script.
Notable updates in this PR:
- Add function to produce a PyBel Signed Graph from a statement dump
- Substantially improve the Explainer class
- Use WrapException in the main script
- Migrate all explanation functions from `depmap_analysis/scripts/depmap_script2.py` to the new file `depmap_analysis/scripts/depmap_script_expl_funcs.py`
- Move several functions from `indra_depmap_service/util.py` to `depmap_analysis/util/io_functions.py`
- Expand the `file_opener` to load objects from S3 if the path provided is a valid S3 path
- This is the first PR where typing is introduced. The idea is to introduce it to all new code from here on in all code that is touched 
for …
> Depmap script update

- depmap_analysis/resources/mito_joined.csv
- depmap_analysis/scripts/depmap_script2.py
This PR adds the file containing genes that are of lesser interest (the "mitochondrial" genes) to the depmap analysis to version control.
> Add mitochondrial file to version control

- depmap_analysis/network_functions/indra_network.py
This PR fixes a bug where the weight parameter to look for in weighted search was hard coded and therefore the wrong parameter were used in some cases.
> Fix weight attribute setting

- depmap_analysis/network_functions/depmap_network_functions.py
- depmap_analysis/scripts/depmap_script2.py
- depmap_analysis/tests/test_script.py
This PR fixes the count of pairs in the main script to represent the count of correlation pairs that will in the end be used, i.e. from the upper/lower triangle.
Two tests for down sampling and for counting pairs are added.
> Report accurate count of notna pair in total

- depmap_analysis/util/aws.py
This PR updates an import from `indra_db` as recent changes broke the imports.
> Update indra_db imports

- .github/workflows/tests.yml
- setup.cfg
- setup.py
- tox.ini
This PR does the following:
1. Adds packaging configuration (`setup.py`/`setup.cfg`)
2. Adds testing configuration with `tox.ini`
3. Adds CI run based on `tox`
> Add packaging config

- depmap_analysis/util/statistics.py
This PR optimizes the `get_n` function which calculates valid sample sizes for pairs of genes and takes a long time. This calculation can be done using a simple dot product which is effectively instantaneous as implemented in the PR.
> Speed up sample size calculation
